InventorySystem/Controllers/AdminController.cs
using InventorySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        ModelContext db = new ModelContext();

        public ActionResult Index()
        {
            
            return View();
        }

        


        public ActionResult SonIslemBilgisi(int info, string returnUrl, string msg = "") {
            // info =>  1=eklendi, 2=silindi, 3=güncellendi
            ViewBag.info = info;
            
            return View();
        }

        public PartialViewResult UserProfil() {
            string username = User.Identity.Name;
            Kullanici user = db.Kullanici.First(n => n.KullaniciAdi == username);
            return PartialView("~/Views/Shared/Partials/UserProfil.cshtml", user);
        }

        public PartialViewResult Menu() {
            string username = User.Identity.Name;
            Kullanici user = db.Kullanici.First(n => n.KullaniciAdi == username);

            return PartialView("~/Views/Shared/Partials/Menu.cshtml", user);
        }

    }
}

InventorySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Envanter Sistemi</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/ionicons.min.css">
    <link rel="stylesheet" href="~/admin-lte/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/admin-lte/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="~/" class="logo">
                <span class="logo-mini"><b>I</b>Sys</span>
                <span class="logo-lg"><b>Inventory</b>System</span>
            </a>
            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @Html.Action("UserProfil", "Admin")
                    </ul>
                </div>
            </nav>
        </header>

        @Html.Action("Menu", "Admin")
        <div class="content-wrapper">
            <section class="content-header"></section>
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; 2018-2019 <a href="#">DeXCoder</a>.</strong> All rights
            reserved.
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/fastclick.js"></script>
    <script src="~/admin-lte/js/adminlte.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
        })
    </script>
</body>
</html>