InventorySystem/Models/Stok.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InventorySystem.Models
{
    public class Stok
    {
        public int StokID { get; set; }

        

        [Display(Name = "Seri Numarası")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        public string SeriNumarasi { get; set; }

        [Display(Name = "Garanti Başlangıç Tarihi")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime GarantiTarihBaslangic { get; set; }

        [Display(Name = "Garanti Bitiş Tarihi")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime GarantiTarihBitis { get; set; }

        [Display(Name = "Malzeme Birim Bedeli")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        public Double MalzemeBirimBedeli { get; set; }

        [Display(Name = "Adet")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        public int Adet { get; set; }

        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }

        [Display(Name = "Kurum")]
        public int KurumID { get; set; }

        [Display(Name = "Malzeme Bilgi")]
        public int MalzemeBilgiID { get; set; }


        public virtual Kurum Kurum { get; set; }
        public virtual MalzemeBilgi MalzemeBilgi { get; set; }
    }
}

InventorySystem/Controllers/StokController.cs
using InventorySystem.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers {

    [Authorize]
    public class StokController : Controller {
        ModelContext db = new ModelContext();


        public ActionResult Index(int sayfa = 1, string q = "") {
            var stoks = db.Stok.Where(n => n.SeriNumarasi.Contains(q) || n.MalzemeBilgi.MalzemeAdi.Contains(q) || n.Kurum.Adi.Contains(q)).ToList();
            return View(stoks.ToPagedList(sayfa, 20));
        }


        [Authorize(Roles = "ST")]
        [HttpGet]
        public ActionResult Ekle() {

            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            Kurum kurum = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum;
            ViewBag.Kurum = kurum.Adi;
            ViewBag.MalzemeBilgiID = new SelectList(db.MalzemeBilgi, "MalzemeBilgiID", "MalzemeAdi");
            return View();
        }

        [Authorize(Roles = "ST")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle([Bind(Include = "MalzemeBilgiID,SeriNumarasi,GarantiTarihBaslangic,GarantiTarihBitis,MalzemeBirimBedeli,Adet,KurumID,Aciklama")] Stok stok) {
            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            Kurum kurum = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum;

            stok.KurumID = kurum.KurumID;
            if (ModelState.IsValid) {
                db.Stok.Add(stok);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            ViewBag.Kurum = kurum.Adi;
            ViewBag.MalzemeBilgiID = new SelectList(db.MalzemeBilgi, "MalzemeBilgiID", "MalzemeAdi");

            return View(stok);
        }

        [Authorize(Roles = "ST")]
        public ActionResult Detay(int? id) {
            if (id == null)
                return RedirectToAction("index");

            Stok stok = db.Stok.FirstOrDefault(n => n.StokID == id);

            return View(stok);
        }

        [HttpGet]
        [Authorize(Roles = "ST")]
        public ActionResult Guncelle(int? id) {
            if (id == null)
                return RedirectToAction("index");

            var stok = db.Stok.Where(n => n.StokID == id).FirstOrDefault();

            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            Kurum kurum = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum;
            ViewBag.Kurum = kurum.Adi;
            ViewBag.MalzemeBilgi = stok.MalzemeBilgi.MalzemeAdi;

            return View(stok);
        }


        [HttpPost]
        [Authorize(Roles = "ST")]
        [ValidateAntiForgeryToken]
        public ActionResult Guncelle([Bind(Include = "StokID,MalzemeBilgiID,SeriNumarasi,GarantiTarihBaslangic,GarantiTarihBitis,MalzemeBirimBedeli,Adet,KurumID,Aciklama")] Stok stok) {
            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            Kurum kurum = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum;
            ViewBag.Kurum = kurum.Adi;
            ViewBag.MalzemeBilgiID = new SelectList(db.MalzemeBilgi, "MalzemeBilgiID", "MalzemeAdi");
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "ST")]
        public ActionResult GuncelleOnayla([Bind(Include = "StokID,MalzemeBilgiID,SeriNumarasi,GarantiTarihBaslangic,GarantiTarihBitis,MalzemeBirimBedeli,Adet,KurumID,Aciklama")] Stok stok) {

            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            Kurum kurum = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum;
            ViewBag.Kurum = kurum.Adi;
            ViewBag.MalzemeBilgi = db.MalzemeBilgi.FirstOrDefault(n => n.MalzemeBilgiID == stok.MalzemeBilgiID).MalzemeAdi;

            Stok eski = db.Stok.FirstOrDefault(n => n.StokID == stok.StokID);
            ViewBag.SeriNumarasi = eski.SeriNumarasi;
            ViewBag.GarantiTarihBaslangic = eski.GarantiTarihBaslangic;
            ViewBag.GarantiTarihBitis = eski.GarantiTarihBitis;
            ViewBag.MalzemeBirimBedeli = eski.MalzemeBirimBedeli;
            ViewBag.Adet = eski.Adet;
            ViewBag.Aciklama = eski.Aciklama;

            return View(stok);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ST")]
        public ActionResult GuncelleOnayli([Bind(Include = "StokID,MalzemeBilgiID,SeriNumarasi,GarantiTarihBaslangic,GarantiTarihBitis,MalzemeBirimBedeli,Adet,KurumID,Aciklama")] Stok stok) {
            String username = User.Identity.Name;
            int userID = db.Kullanici.FirstOrDefault(n => n.KullaniciAdi == username).KullaniciID;
            stok.KurumID = db.Kullanici.FirstOrDefault(n => n.KullaniciID == userID).Birim.Kurum.KurumID;
            if (ModelState.IsValid) {
                db.Entry(stok).State = EntityState.Modified;
                db.SaveChanges();
            } else {
                return Content("hata oluştu");
            }
            return RedirectToAction("Detay", new { id = stok.StokID });
        }


        [Authorize(Roles = "ST")]
        public ActionResult Sil(int? id) {
            Stok stok = db.Stok.FirstOrDefault(n => n.StokID == id);
            if (id == null)
                RedirectToAction("Index");


            return View(stok);
        }

        [Authorize(Roles = "ST")]
        public ActionResult SilOnayla(int? id) {
            
            if (id == null)
                RedirectToAction("Index");


            return RedirectToAction("Index");
        }
    }


}

InventorySystem/Views/Stok/Detay.cshtml
@model InventorySystem.Models.Stok

@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Stok Bilgisi Detayları</h3>
    </div>
    <div class="box-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.LabelFor(model => model.MalzemeBilgi.MalzemeAdi)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.MalzemeBilgi.MalzemeAdi)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Kurum.Adi)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Kurum.Adi)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Adet)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Adet)
            </dd>

            <dt>
                @Html.LabelFor(model => model.MalzemeBirimBedeli)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.MalzemeBirimBedeli)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Aciklama)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Aciklama)
            </dd>

            <dt>
                @Html.LabelFor(model => model.GarantiTarihBaslangic)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.GarantiTarihBaslangic)
            </dd>

            <dt>
                @Html.LabelFor(model => model.GarantiTarihBitis)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.GarantiTarihBitis)
            </dd>
        </dl>
    </div>

    <div class="box-footer">
        @Html.ActionLink("Listeye Dön", "Index", null, new { @class = "btn btn-flat btn-warning" })

        @if (User.IsInRole("ST")) {
            @Html.ActionLink("Bilgileri Güncelle", "Guncelle", new { id = Model.StokID }, new { @class = "btn btn-flat btn-info" })
        }

        @if (User.IsInRole("ST")) {
            @Html.ActionLink("Sil", "Sil", new { id = Model.StokID }, new { @class = "btn btn-flat btn-danger" })
        }

    </div>
</div>

InventorySystem/Views/Stok/Ekle.cshtml
@model InventorySystem.Models.Stok

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Yeni Stok Kaydı Ekle</h3>
    </div>
    <div class="box-body">
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            <br />
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.MalzemeBilgiID, "MalzemeBilgiID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("MalzemeBilgiID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MalzemeBilgiID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SeriNumarasi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SeriNumarasi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SeriNumarasi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GarantiTarihBaslangic, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GarantiTarihBaslangic, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.GarantiTarihBaslangic, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GarantiTarihBitis, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GarantiTarihBitis, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.GarantiTarihBitis, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MalzemeBirimBedeli, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MalzemeBirimBedeli, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MalzemeBirimBedeli, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adet, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adet, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KurumID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select class="form-control" disabled>
                            <option>
                                @ViewBag.Kurum
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="box-footer">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kayıt Ekle" class="btn btn-success btn-flat" />
                        @Html.ActionLink("Listeye Dön", "Index", null, new { @class = "btn btn-warning btn-flat" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

InventorySystem/Views/Stok/Guncelle.cshtml
@model InventorySystem.Models.Stok

@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Malzeme Bilgilerini Güncelle</h3>
    </div>
    <div class="box-body">
        @using (Html.BeginForm("GuncelleOnayla", "Stok")) {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Stok</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.StokID)

                <div class="form-group">
                    @Html.LabelFor(model => model.MalzemeBilgiID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select class="form-control" disabled="disabled">
                            <option selected="selected">@ViewBag.MalzemeBilgi</option>
                        </select>
                    </div>
                </div>
                <input type="hidden" name="MalzemeBilgiID" value="@Model.MalzemeBilgiID" />

                <div class="form-group">
                    @Html.LabelFor(model => model.SeriNumarasi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SeriNumarasi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SeriNumarasi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GarantiTarihBaslangic, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.GarantiTarihBaslangic, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                        @Html.ValidationMessageFor(model => model.GarantiTarihBaslangic, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GarantiTarihBitis, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.GarantiTarihBitis, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                        @Html.ValidationMessageFor(model => model.GarantiTarihBitis, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MalzemeBirimBedeli, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MalzemeBirimBedeli, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MalzemeBirimBedeli, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adet, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adet, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KurumID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select class="form-control" disabled>
                            <option>
                                @ViewBag.Kurum
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="box-footer">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Güncelle" class="btn btn-success btn-flat" />
                        @Html.ActionLink("Listeye Dön", "Index", null, new { @class = "btn btn-warning btn-flat" })
                    </div>
                </div>

            </div>
        }
    </div>
</div>

InventorySystem/Views/Stok/GuncelleOnayla.cshtml
@model InventorySystem.Models.Stok

@{
    ViewBag.Title = "Guncellemeyi Onayla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.MalzemeBilgi</h3>
    </div>

    <div class="box-body">
        <div class="col-md-6">
            <div class="form-horizontal">
                <h4>Eski Bilgiler</h4>
                <hr />

                <table class="table table-hover table-inverse">
                    <tr>
                        <td>Seri Numarası</td>
                        <td>@ViewBag.SeriNumarasi</td>
                    </tr>

                    <tr>
                        <td>Garanti Başlangıç Tarihi</td>
                        <td>@ViewBag.GarantiTarihBaslangic.ToString("dd.MM.yyyy")</td>
                    </tr>

                    <tr>
                        <td>Garanti Bitiş Tarihi</td>
                        <td>@ViewBag.GarantiTarihBitis.ToString("dd.MM.yyyy")</td>
                    </tr>

                    <tr>
                        <td>Malzeme Birim Bedeli</td>
                        <td>@ViewBag.MalzemeBirimBedeli</td>
                    </tr>

                    <tr>
                        <td>Adet</td>
                        <td>@ViewBag.Adet</td>
                    </tr>

                    <tr>
                        <td>Açıklama</td>
                        <td>@ViewBag.Aciklama</td>
                    </tr>

                </table>

            </div>
        </div>
        <div class="col-md-6">
            @using (Html.BeginForm("GuncelleOnayli", "Stok")) {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Yeni Bilgiler</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.StokID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.MalzemeBilgiID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" disabled>
                                <option>
                                    @ViewBag.MalzemeBilgi
                                </option>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="MalzemeBilgiID" value="@Model.MalzemeBilgiID" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.SeriNumarasi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SeriNumarasi, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.SeriNumarasi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="SeriNumarasi" value="@Model.SeriNumarasi" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.GarantiTarihBaslangic, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GarantiTarihBaslangic, new { htmlAttributes = new { @class = "form-control", type = "date", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.GarantiTarihBaslangic, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="GarantiTarihBaslangic" value="@Model.GarantiTarihBaslangic" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.GarantiTarihBitis, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GarantiTarihBitis, new { htmlAttributes = new { @class = "form-control", type = "date", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.GarantiTarihBitis, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="GarantiTarihBitis" value="@Model.GarantiTarihBitis" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.MalzemeBirimBedeli, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MalzemeBirimBedeli, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.MalzemeBirimBedeli, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="MalzemeBirimBedeli" value="@Model.MalzemeBirimBedeli" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Adet, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Adet, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.Adet, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="Adet" value="@Model.Adet" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.KurumID, htmlAttributes: new { @class = "control-label col-md-2", disabled = "disabled" })
                        <div class="col-md-10">
                            <select class="form-control" disabled>
                                <option>
                                    @ViewBag.Kurum
                                </option>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="KurumID" value="@Model.KurumID" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <input type="hidden" name="Aciklama" value="@Model.Aciklama" />

                    <div class="box-footer">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Onayla ve Güncelle" class="btn btn-success btn-flat" />
                            @Html.ActionLink("Vazgeç", "Index", null, new { @class = "btn btn-warning btn-flat" })
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

InventorySystem/Views/Stok/Index.cshtml
@using PagedList
@using PagedList.Mvc

@model IEnumerable<InventorySystem.Models.Stok>

@{
    ViewBag.Title = "Stok";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int counter = 0;
    if (Request.Params.Get("sayfa") != null && !Convert.ToInt32(Request.Params.Get("sayfa")).Equals(1)) {
        counter = 20 * (Convert.ToInt32(Request.Params.Get("sayfa")) - 1);
    }

    var q = Request.Params.Get("q");
}


<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Stok</h3>
        @if (User.IsInRole("ST")) {
            <div class="pull-right">
                @Html.ActionLink("Yeni Kayıt Ekle", "Ekle", null, new { @class = "btn btn-success btn-flat" })
            </div>
        }
        <br clear="all" />
        @if (q != null) {
            <div class="callout callout-warning">
                <h2><b class="text-red">@q</b> için arama sonuçları listeleniyor</h2>
            </div>
        }
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>#.</th>
                    <th>Seri Numarası</th>
                    <th>Malzeme Adı</th>
                    <th>Kurum</th>
                    <th>Adet</th>
                    <th>Malzeme Birim Bedeli</th>
                    <th>Garanti Baş. Bit. Tarihleri</th>
                    <th>Açıklama</th>

                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model) {
                    counter++;
                <tr>
                    <td>@counter</td>
                    <td>
                        @Html.ActionLink(item.SeriNumarasi, "Detay", new { id = item.StokID })
                    </td>
                    <td>
                        @item.MalzemeBilgi.MalzemeAdi
                    </td>
                    <td>@item.Kurum.Adi</td>
                    <td>@item.Adet</td>
                    <td>@item.MalzemeBirimBedeli</td>
                    <td>@item.GarantiTarihBaslangic.ToString("dd.MM.yyyy") <br /> @item.GarantiTarihBitis.ToString("dd.MM.yyyy")</td>
                    <td>@item.Aciklama</td>

                </tr>
                }
            </tbody>
        </table>
        <div class="pull-right">
            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa, q }), PagedListRenderOptions.ClassicPlusFirstAndLast)
        </div>
    </div>
</div>