InventorySystem/Controllers/YonetimController.cs
using InventorySystem.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers {

    [Authorize]
    public class YonetimController : Controller {

        ModelContext db = new ModelContext();

        public ActionResult Index() {
            return View();
        }

        // birim
        [HttpGet]
        public ActionResult BirimEkle() {
            ViewBag.KurumID = new SelectList(db.Kurum, "KurumID", "Adi");
            return View();
        }

        [HttpPost]
        public ActionResult BirimEkle([Bind(Include = "Adi, KurumID")] Birim birim) {
            if (ModelState.IsValid) {
                db.Birim.Add(birim);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KurumID = new SelectList(db.Kurum, "KurumID", "Adi", birim.KurumID);
            return View();
        }



        // kurum
        [HttpGet]
        public ActionResult KurumEkle() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KurumEkle([Bind(Include = "Adi")] Kurum kurum) {
            if (ModelState.IsValid) {
                db.Kurum.Add(kurum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kurum);
        }


        //kullanici




        // Partial lists
        public PartialViewResult KullaniciList(int kullanici = 1, int kurum = 1, int birim = 1) {
            ViewBag.birim = birim;
            ViewBag.kullanici = kullanici;
            ViewBag.kurum = kurum;

            List<Kullanici> k = db.Kullanici.ToList();
            return PartialView("~/Views/Yonetim/Partials/KullaniciList.cshtml", k.ToPagedList(kullanici, 10));
        }

        public PartialViewResult KurumList(int kullanici = 1, int kurum = 1, int birim = 1) {
            ViewBag.birim = birim;
            ViewBag.kullanici = kullanici;
            ViewBag.kurum = kurum;

            List<Kurum> k = db.Kurum.ToList();
            return PartialView("~/Views/Yonetim/Partials/KurumList.cshtml", k.ToPagedList(kurum, 10));
        }

        public PartialViewResult BirimList(int kullanici = 1, int kurum = 1, int birim = 1) {
            ViewBag.birim = birim;
            ViewBag.kullanici = kullanici;
            ViewBag.kurum = kurum;

            List<Birim> b = db.Birim.ToList();

            return PartialView("~/Views/Yonetim/Partials/BirimList.cshtml", b.ToPagedList(birim, 10));
        }


    }
}

InventorySystem/Views/Yonetim/BirimEkle.cshtml
@model InventorySystem.Models.Birim

@{
    ViewBag.Title = "Birim Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Yeni Birim Ekle</h3>
    </div>
    <div class="box-body">
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            <br />
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KurumID, "Kurum Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KurumID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KurumID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="box-footer">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Birim Ekle" class="btn btn-success btn-flat" />
                        @Html.ActionLink("Listeye Dön", "Index", null, new { @class = "btn btn-warning btn-flat" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

InventorySystem/Views/Yonetim/Index.cshtml
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Kullanıcı Yönetimi</h3>
            <div class="pull-right">
                @Html.ActionLink("Yeni Kullanıcı Ekle", "KullaniciEkle", null, new { @class = "btn btn-flat btn-success" })
            </div>
        </div>
        <div class="box-body">
            @Html.Action("KullaniciList", "Yonetim")
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Kurum Yönetimi</h3>
            <div class="pull-right">
                @Html.ActionLink("Yeni Kurum Ekle", "KurumEkle", null, new { @class = "btn btn-flat btn-success" })
            </div>
        </div>
        <div class="box-body">
            @Html.Action("KurumList", "Yonetim")
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Birim Yönetimi</h3>
            <div class="pull-right">
                @Html.ActionLink("Yeni Birim Ekle", "BirimEkle", null, new { @class = "btn btn-flat btn-success" })
            </div>
        </div><div class="box-body">
            @Html.Action("BirimList", "Yonetim")
        </div>
    </div>
</div>

<br clear="all" />

InventorySystem/Views/Yonetim/KurumEkle.cshtml
@model InventorySystem.Models.Kurum

@{
    ViewBag.Title = "KurumEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Yeni Kurum Ekle</h3>
    </div>
    <div class="box-body">
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Ekle" class="btn btn-flat btn-success" />
                        @Html.ActionLink("Listeye Dön", "Index", null, new { @class = "btn btn-flat btn-warning" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>